### ISSUE TITLE
Changing variable values while debugging

### ISSUE THREAD

**Issue by cnunn29** [FourjsGenero/tool_fgldeb#2]
Hi

This is a great tool for genero, but there doesn't appear to be an option to change a variable value when debugging.

If there an updated version with this option, its has just about everything except this option unless I'm not seeing it.

Hope you can help.

**Comment by cnunn29** [comment]
use

set variable fv_count=2

**Comment by sebflaesch** [comment]
Hello,
Did you consider testing our latest Genero BDL versions 4.01 or 5.00, having our VSCode extension?
https://4js.com/online_documentation/fjs-fgl-manual-html/#fgl-topics/c_fgl_CodeEditing_006.html
Seb
